# Site settings
title: Personal Library
description: A collection of texts and documents
url: "https://merdeki.github.io"
baseurl: "/kutuphane"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  texts:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "texts"
    values:
      layout: "text"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
